server:
  port: 8088
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB #MB¥Û–¥
      max-request-size: 100MB
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
    template-loader-path: classpath:/templates

